#!/bin/bash

# 🧹 ADP SESSION CLEANUP SCRIPT
# Auto-generated by Session Diagnostic Tool

echo "🧹 ADP SESSION CLEANUP STARTING"
echo "==============================="

# Kill browser processes
echo "1️⃣  Killing browser processes..."
killall "Google Chrome" 2>/dev/null || echo "   Chrome not running"
killall "Safari" 2>/dev/null || echo "   Safari not running"
killall "Firefox" 2>/dev/null || echo "   Firefox not running"
killall "playwright" 2>/dev/null || echo "   Playwright not running"

# Clear temp directories
echo "2️⃣  Clearing temp directories..."
rm -rf /tmp/playwright-* 2>/dev/null || echo "   No Playwright temp dirs"
rm -rf /tmp/chrome-* 2>/dev/null || echo "   No Chrome temp dirs"

# Flush DNS
echo "3️⃣  Flushing DNS cache..."
sudo dscacheutil -flushcache 2>/dev/null || echo "   DNS flush failed (need sudo)"

# Wait for cleanup
echo "4️⃣  Waiting for system cleanup..."
sleep 5

echo "✅ Cleanup completed!"
echo ""
echo "🎯 NEXT STEPS:"
echo "1. Wait 10 minutes for ADP server session timeout"
echo "2. Manually clear browser data for ADP domains"
echo "3. Run your automation test again"
echo ""
echo "⏰ Current time: $(date)"
echo "🕒 Run test after: $(date -v+10M)"
